language: cpp
compiler:
      - gcc
      - clang
env: OMP_NUM_THREADS=4
before_install:
      - sudo apt-get update -qq
install:
      - sudo apt-get install -qq cmake libsndfile1-dev libasound2-dev libjack-dev portaudio19-dev libportmidi-dev libpulse-dev swig liblua5.1-0-dev python-dev puredata-dev default-jdk libfltk1.1-dev libfluidsynth-dev liblo-dev fluid ladspa-sdk libboost-dev libboost-serialization-dev libpng-dev dssi-dev libstk0-dev libgmm++-dev bison flex libportsmf-dev libeigen3-dev
before_script:
      - mkdir build
script:
      - cd build && cmake .. && make && make check


