language: cpp
compiler:
      - gcc
      - clang
env:
      global:
           - secure: JxNTr0zTdQ6KNsVQgQYL9acqTWege7VeblmRQ4bb4he5WyIViyrXvrrss111EVimoC37qKFMHzL/yDh2hbNHW26ZIGcIKvNduO5IeixglJMun2h4FYtVjRc+iBCm+sL7RceB1usDLXk1+QFlvN9iMJqgHfjCZ1/rzIg+BSZ6llU=
           - OMP_NUM_THREADS=4
           - VERBOSE=1
before_install:
      - sudo apt-get update -qq
install:
      - sudo apt-get install -qq cmake libsndfile1-dev libasound2-dev libjack-dev portaudio19-dev libportmidi-dev libpulse-dev swig liblua5.1-0-dev python-dev puredata-dev default-jdk libfltk1.1-dev libfluidsynth-dev liblo-dev fluid ladspa-sdk libboost-dev libboost-serialization-dev libpng-dev dssi-dev libstk0-dev libgmm++-dev bison flex libportsmf-dev libeigen3-dev libcunit1-dev
before_script:
      - mkdir build
script:
      - cd build && cmake .. -DBUILD_STATIC_LIBRARY=ON -DBUILD_TESTS=ON && make && make test

addons:
      coverity_scan:
          project:
              name: "fsateler/csound"
              description: "Your project description here"
          notification_email: csound-devel@lists.sourceforge.net
          build_command_prepend: "mkdir build && cd build && cmake .."
          build_command: "make -C build"
          branch_pattern: coverity_scan
