image: Visual Studio 2015

environment:
  QTDIR: C:\Qt\5.9.1\msvc2015_64
  VCPKGDir: C:\Tools\vcpkg

install:
  - set
  - cd msvc
  # This is for compatibility with Windows 8.
  - powershell -ExecutionPolicy ByPass -File downloadDependencies.ps1 -vsGenerator "Visual Studio 14 2015 Win64" -vsToolset "v140_xp"
  - powershell -ExecutionPolicy ByPass -File generateProject.ps1 -vsGenerator "Visual Studio 14 2015 Win64" -vsToolset "v140_xp"
  - cd ..

platform: x64

configuration: Release

build:
  parallel: true
  project: msvc\csound-vs\Csound.sln

after_build:
  - dir "%VCPKGDir%\installed\x64-windows\include"
  - if %APPVEYOR_BUILD_WORKER_IMAGE% == "Visual Studio 2017" call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
  - if %APPVEYOR_BUILD_WORKER_IMAGE% == "Visual Studio 2015" call "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\vcvars64.bat"
  - set PATH=%QTDIR%\bin;%PATH%
  - cd msvc
  # Report qmake version to make sure we are using the Qt libraries we need.
  - qmake -v
  - build_csoundqt.bat
  - cd ..
  - set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"
  - iscc /dVcpkgInstalledBinDir=%VCPKGDir%\\installed\\x64-windows\\bin\\ /dQtSdkBinDir=%QTDIR%\\bin\\ /omsvc installer\\windows\\csound6_x64_appveyor.iss
  - 7z a csound.zip %APPVEYOR_BUILD_FOLDER%\msvc\csound-vs\Release\*.exe %APPVEYOR_BUILD_FOLDER%\msvc\csound-vs\Release\csound64.lib %APPVEYOR_BUILD_FOLDER%\include\ %APPVEYOR_BUILD_FOLDER%\msvc\csound-vs\Release\*.dll %APPVEYOR_BUILD_FOLDER%\msvc\csound-vs\Release\*.pyd %APPVEYOR_BUILD_FOLDER%\msvc\csound-vs\*.jar %APPVEYOR_BUILD_FOLDER%\msvc\csound-vs\*.py %APPVEYOR_BUILD_FOLDER%\msvc\staging\CsoundQt\bin\*.exe
  - 7z l csound.zip

artifacts:
  - path: csound.zip
    name: Csound
    type: zip
  - path: msvc/Setup_Csound_x64_6.09.2beta3.exe
    name: Csound Installer
    type: exe

cache:
 - C:\Tools\vcpkg\ -> C:\projects\csound\msvc\downloadDependencies.ps1
 - C:\projects\csound\msvc\cache

#deploy:
#  release: myproduct-v$(appveyor_build_version)
#  description: 'Release description'
#  provider: GitHub
#  auth_token:
#    secure: <your encrypted token> # your encrypted token from GitHub
#  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    appveyor_repo_tag: true        # deploy on tag push only

notifications:
  - provider: Email
    to:
      - CSOUND-DEV@listserv.heanet.ie
    subject: 'Build {{status}}'     # optional
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

#  - provider: Slack
#    auth_token:
#      secure: kBl9BlxvRMr9liHmnBs14A==
#    channel: development
#    template: "{{template_variable_1}}, {{template_variable_2}}, ..."
